#!/bin/bash

# Set URL to search for kernel updates

BASE=https://kernel.ubuntu.com/~kernel-ppa/mainline/
VERSION=v5.16

URL=$BASE$VERSION/amd64/
echo "Querying for versions" $URL

#Prompt user for which version of the kernel should be installed

mapfile -t VERSIONS < <(curl -sS $URL | grep -oP '(linux-header).*?(.deb)' | grep -oP '(generic).*?(amd64)' | uniq) 

echo "What version should be installed"
i=0
for ver in "${VERSIONS[@]}";
do
	echo $i ") " $ver
	i=$((i+1))
done

read VERSIONNUM

VERSIONCHOICE=${VERSIONS[$VERSIONNUM]}

# download all the associated files
echo "Downloading kernel files"

mapfile -t FILES < <(curl -sS $URL | grep -oP "(linux-).*?($VERSIONCHOICE)(.deb)" | uniq)

for FILE in "${FILES[@]}";
do
	wget -q $URL$FILE
done

# Validate the checksums
wget -q $URL/CHECKSUMS

if ! $(shasum -c -s --ignore-missing CHECKSUMS); 
then
	echo "Downloaded files don't match checksums. Exiting"
	exit 1
fi

# Install the downloaded files

sudo chmod +x *.deb
sudo dpkg -i *.deb

echo "Reboot to update kernel"
